#############################################################################
# Makefile for building: kodoi_server
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  kodoi_server.pro
# Template: app
# Command: /home/max/soft/Qt/5.12.3/gcc_64/bin/qmake -o Makefile kodoi_server.pro -config release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../soft/Qt/5.12.3/gcc_64/include -I../../../soft/Qt/5.12.3/gcc_64/include/QtGui -I../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork -I../../../soft/Qt/5.12.3/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../soft/Qt/5.12.3/gcc_64/mkspecs/linux-g++
QMAKE         = /home/max/soft/Qt/5.12.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/max/soft/Qt/5.12.3/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/max/soft/Qt/5.12.3/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kodoi_server1.0.0
DISTDIR = /home/max/qt_projects/kodoi_server_dir/kodoi_server/.tmp/kodoi_server1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/max/soft/Qt/5.12.3/gcc_64/lib
LIBS          = $(SUBLIBS) -static -L/home/max/soft/Qt/5.12.3/gcc_64/lib -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = AbstractBoard.cpp \
		Board.cpp \
		ClientSession.cpp \
		Club.cpp \
		Message.cpp \
		Response.cpp \
		Room.cpp \
		TCPServer.cpp \
		main.cpp moc_TCPServer.cpp
OBJECTS       = AbstractBoard.o \
		Board.o \
		ClientSession.o \
		Club.o \
		Message.o \
		Response.o \
		Room.o \
		TCPServer.o \
		main.o \
		moc_TCPServer.o
DIST          = ../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		kodoi_server.pro AbstractBoard.h \
		Board.h \
		ClientSession.h \
		Club.h \
		Message.h \
		Response.h \
		Room.h \
		TCPServer.h \
		helpers.h \
		types.h AbstractBoard.cpp \
		Board.cpp \
		ClientSession.cpp \
		Club.cpp \
		Message.cpp \
		Response.cpp \
		Room.cpp \
		TCPServer.cpp \
		main.cpp
QMAKE_TARGET  = kodoi_server
DESTDIR       = 
TARGET        = kodoi_server


first: all
####### Build rules

kodoi_server:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kodoi_server.pro ../../../soft/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		kodoi_server.pro \
		../../../soft/Qt/5.12.3/gcc_64/lib/libQt5Gui.prl \
		../../../soft/Qt/5.12.3/gcc_64/lib/libQt5Network.prl \
		../../../soft/Qt/5.12.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile kodoi_server.pro -config release
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qt.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/moc.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/unix/opengl.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/unix/thread.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf:
../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf:
kodoi_server.pro:
../../../soft/Qt/5.12.3/gcc_64/lib/libQt5Gui.prl:
../../../soft/Qt/5.12.3/gcc_64/lib/libQt5Network.prl:
../../../soft/Qt/5.12.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile kodoi_server.pro -config release

qmake_all: FORCE


all: Makefile kodoi_server

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents AbstractBoard.h Board.h ClientSession.h Club.h Message.h Response.h Room.h TCPServer.h helpers.h types.h $(DISTDIR)/
	$(COPY_FILE) --parents AbstractBoard.cpp Board.cpp ClientSession.cpp Club.cpp Message.cpp Response.cpp Room.cpp TCPServer.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../soft/Qt/5.12.3/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_TCPServer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TCPServer.cpp
moc_TCPServer.cpp: TCPServer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QObject \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpSocket \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpServer \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpserver.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qhostaddress.h \
		ClientSession.h \
		Club.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		Room.h \
		Board.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		Response.h \
		moc_predefs.h \
		../../../soft/Qt/5.12.3/gcc_64/bin/moc
	/home/max/soft/Qt/5.12.3/gcc_64/bin/moc $(DEFINES) --include /home/max/qt_projects/kodoi_server_dir/kodoi_server/moc_predefs.h -I/home/max/soft/Qt/5.12.3/gcc_64/mkspecs/linux-g++ -I/home/max/qt_projects/kodoi_server_dir/kodoi_server -I/home/max/soft/Qt/5.12.3/gcc_64/include -I/home/max/soft/Qt/5.12.3/gcc_64/include/QtGui -I/home/max/soft/Qt/5.12.3/gcc_64/include/QtNetwork -I/home/max/soft/Qt/5.12.3/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include TCPServer.h -o moc_TCPServer.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

AbstractBoard.o: AbstractBoard.cpp AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractBoard.o AbstractBoard.cpp

Board.o: Board.cpp Board.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutexLocker
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Board.o Board.cpp

ClientSession.o: ClientSession.cpp ../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutexLocker \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		ClientSession.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpSocket \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		Club.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		Room.h \
		Board.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		Response.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientSession.o ClientSession.cpp

Club.o: Club.cpp ../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutexLocker \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		Club.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		Room.h \
		Board.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		ClientSession.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpSocket \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair \
		Response.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Club.o Club.cpp

Message.o: Message.cpp ../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QString \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		helpers.h \
		Board.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Message.o Message.cpp

Response.o: Response.cpp Response.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		Board.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Response.o Response.cpp

Room.o: Room.cpp Room.h \
		Board.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		ClientSession.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpSocket \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		Club.h \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		Response.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutexLocker
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Room.o Room.cpp

TCPServer.o: TCPServer.cpp TCPServer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QObject \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpSocket \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpServer \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpserver.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qhostaddress.h \
		ClientSession.h \
		Club.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		Room.h \
		Board.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		Response.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TCPServer.o TCPServer.cpp

main.o: main.cpp ../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QCoreApplication \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qconfig.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtcore-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlogging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qflags.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmutex.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnumeric.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstring.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qchar.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qrefcount.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qnamespace.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qarraydata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringliteral.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringview.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiterator.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpair.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringlist.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qregexp.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmetatype.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qeventloop.h \
		TCPServer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QObject \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpSocket \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qiodevice.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qdebug.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qhash.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qmap.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qtextstream.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qlocale.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvariant.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qshareddata.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qvector.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qpoint.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qset.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/QTcpServer \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qtcpserver.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtNetwork/qhostaddress.h \
		ClientSession.h \
		Club.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QMutex \
		Room.h \
		Board.h \
		AbstractBoard.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QVector \
		helpers.h \
		cereal/archives/binary.hpp \
		cereal/cereal.hpp \
		cereal/macros.hpp \
		cereal/details/traits.hpp \
		cereal/access.hpp \
		cereal/specialize.hpp \
		cereal/details/helpers.hpp \
		cereal/details/static_object.hpp \
		cereal/types/base_class.hpp \
		cereal/details/polymorphic_impl_fwd.hpp \
		cereal/types/common.hpp \
		types.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QPair \
		Message.h \
		../../../soft/Qt/5.12.3/gcc_64/include/QtCore/QByteArray \
		Response.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_TCPServer.o: moc_TCPServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TCPServer.o moc_TCPServer.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/kodoi_server/bin || mkdir -p $(INSTALL_ROOT)/opt/kodoi_server/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/kodoi_server/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/kodoi_server/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/kodoi_server/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/kodoi_server/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

